---
- name: Set LoginGraceTime to 0 on SSH
  become: true
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#LoginGraceTime'
    line: LoginGraceTime
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^LoginGraceTime'
    line: LoginGraceTime 0
  notify: Restart service ssh